name: CI

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:

  CheckoutCode:
    runs-on: ubuntu-latest

    steps:
    - name: chekcout code
      uses: actions/checkout@v4
      
    - name: list code
      run: ls -l
  DockerLogin:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker 
        uses: docker/setup-docker-action@v5.5.0
      - uses: actions/checkout@v4
      - name: Login to docker
        run: |
          docker build . -t abobakryousre/first-app
          echo "image created"
          echo '${{ secrets.dockerPassword }} | docker login -u ${{ secrets.dockerUser }} --password-stdin'
          docker push abobakryousre/first-app
